Loom: Instrumentation Class Reference
Instrumentation Class Reference
Instrumentation code (which could be a function or inline instructions) that receives program events such as "called foo(42,97)" and takes policy-defined actions (e.g., logs events or updates counters).
#include <Instrumentation.hh>
Public Member Functions
Instrumentation (llvm::SmallVector< llvm::Value *, 4 > Values, llvm::BasicBlock *Preamble, llvm::BasicBlock *EndBlock, llvm::Instruction *PreambleEnd, llvm::Instruction *End)
Construct some instrumentation that puts all actions into BasicBlocks injected between the specified preamble and end blocks.
Instrumentation (llvm::SmallVector< llvm::Value *, 4 > Values, llvm::Instruction *PreambleEnd, llvm::Instruction *End)
Construct some instrumentation that directly injects actions as inline instructions rather than using BasicBlocks.
llvm::ArrayRef< llvm::Value * > Values ()
Retrieve the values passed into the instrumentation.
llvm::IRBuilder GetBuilder ()
Get an IRBuilder to insert instructions into the instrumentation preamble.
llvm::IRBuilder AddAction (llvm::StringRef Name)
Add a new link in the chain of actions for this instrumentation.
Detailed Description
Instrumentation code (which could be a function or inline instructions) that receives program events such as "called foo(42,97)" and takes policy-defined actions (e.g., logs events or updates counters).
Definition at line 62 of file Instrumentation.hh.
Constructor & Destructor Documentation
Instrumentation() [1/2]
Instrumentation (llvm::SmallVector< llvm::Value *, 4 > Values, llvm::BasicBlock * Preamble, llvm::BasicBlock * EndBlock, llvm::Instruction * PreambleEnd, llvm::Instruction * End)
Construct some instrumentation that puts all actions into BasicBlocks injected between the specified preamble and end blocks.
Instrumentation() [2/2]
Instrumentation (llvm::SmallVector< llvm::Value *, 4 > Values, llvm::Instruction * PreambleEnd, llvm::Instruction * End)
Construct some instrumentation that directly injects actions as inline instructions rather than using BasicBlocks.
Member Function Documentation
AddAction()
llvm::IRBuilder AddAction (llvm::StringRef Name)
Add a new link in the chain of actions for this instrumentation.
Referenced by Instrumentation::GetBuilder().
GetBuilder()
IRBuilder GetBuilder ()
Get an IRBuilder to insert instructions into the instrumentation preamble.
The preamble is a block where we can put instructions that should run whenever the instrumentation is called, regardless of the values that are passed into it. This could be used to implement gprof-style counting or simple logging.
Definition at line 71 of file Instrumentation.cc.
References Instrumentation::AddAction().
Values()
llvm::ArrayRef<llvm::Value*> Values () inline
Retrieve the values passed into the instrumentation.
Definition at line 80 of file Instrumentation.hh.
Referenced by Instrumenter::Instrument().
The documentation for this class was generated from the following files:
src/Instrumentation.hh
src/Instrumentation.cc