Loom: NVSerializer Class Reference
NVSerializer Class Reference
A Serializer that uses libnv to aggregate values.
#include <NVSerializer.hh>
Public Member Functions
NVSerializer (llvm::Module &)
virtual llvm::StringRef SchemeName () const override
A unique name that identifies the serialization scheme (e.g., nvlist).
virtual BufferInfo Serialize (llvm::StringRef Name, llvm::StringRef Descrip, llvm::ArrayRef< llvm::Value *>, llvm::IRBuilder<> &) override
Generate the code to serialize a set of values, returning details of the resulting buffer (pointer and length).
virtual llvm::Instruction * Cleanup (BufferInfo &, llvm::IRBuilder<> &) override
Clean up a serialized data buffer using Serializer-specific cleanup code (e.g., free() or nvlist_destroy).
Additional Inherited Members
Public Types inherited from Serializer
typedef std::pair< llvm::Value *, llvm::Value * > BufferInfo
A buffer can be described using a pointer and a length.
Static Public Member Functions inherited from Serializer
static std::unique_ptr< Serializer > None ()
Create an empty Serializer unique_ptr.
Protected Member Functions inherited from Serializer
Serializer (llvm::LLVMContext &Ctx)
Protected Attributes inherited from Serializer
llvm::LLVMContext & Ctx
llvm::IntegerType * Byte
llvm::PointerType * BytePtr
llvm::IntegerType * SizeT
Detailed Description
A Serializer that uses libnv to aggregate values.
Definition at line 45 of file NVSerializer.hh.
Member Function Documentation
Cleanup()
virtual llvm::Instruction* Cleanup (BufferInfo & , llvm::IRBuilder<> &) override virtual
Clean up a serialized data buffer using Serializer-specific cleanup code (e.g., free() or nvlist_destroy).
Implements Serializer.
Referenced by NVSerializer::SchemeName().
SchemeName()
virtual llvm::StringRef SchemeName () const inline override virtual
A unique name that identifies the serialization scheme (e.g., nvlist).
Implements Serializer.
Definition at line 49 of file NVSerializer.hh.
References NVSerializer::Cleanup(), and NVSerializer::Serialize().
Serialize()
virtual BufferInfo Serialize (llvm::StringRef Name, llvm::StringRef Descrip, llvm::ArrayRef< llvm::Value *> Values, llvm::IRBuilder<> & B) override virtual
Generate the code to serialize a set of values, returning details of the resulting buffer (pointer and length).
Parameters
Name Machine-readable instrumentation name.
Description Human-readable short description (may be ignored).
Values Values actually being serialized
B IRBuilder positioned within instrumentation code
Implements Serializer.
Referenced by NVSerializer::SchemeName().
The documentation for this class was generated from the following files:
src/NVSerializer.hh
src/NVSerializer.cc