Loom: Instrumenter Class Reference
Instrumenter Class Reference
An object used for instrumenting code within a single LLVM module.
#include <Instrumenter.hh>
Public Types
typedef std::function< std::string(const std::vector< std::string > &)> NameFn
Public Member Functions
bool Instrument (llvm::Instruction *)
Instrument an instruction generically: instruction name and values.
bool Instrument (llvm::CallInst *, const Policy::Directions &)
Instrument a function call in the call and/or return direction.
bool Instrument (llvm::CallInst *Call, Policy::Direction)
Instrument a function call (caller-side), either calling or returning.
bool Instrument (llvm::Function &, const Policy::Directions &)
Instrument a function entry and/or exit.
bool Instrument (llvm::Function &, Policy::Direction)
Instrument a function entry or exit.
bool Instrument (llvm::GetElementPtrInst *, llvm::LoadInst *, llvm::StringRef FieldName)
Instrument a read from a structure field.
bool Instrument (llvm::GetElementPtrInst *, llvm::StoreInst *, llvm::StringRef FieldName)
Instrument a write to a structure field.
Static Public Member Functions
static std::unique_ptr< Instrumenter > Create (llvm::Module &, NameFn NF, std::unique_ptr< InstrStrategy > S)
Create a new Instrumenter instance.
Detailed Description
An object used for instrumenting code within a single LLVM module.
Definition at line 47 of file Instrumenter.hh.
Member Function Documentation
Create()
static std::unique_ptr<Instrumenter> Create (llvm::Module & , NameFn NF, std::unique_ptr< InstrStrategy > S) static
Create a new Instrumenter instance.
Parameters
NF a function that can be called to name instrumentation (e.g., ["call","foo"] => "__loom_hook_call_foo")
Instrument() [1/7]
bool Instrument (llvm::Instruction * I)
Instrument an instruction generically: instruction name and values.
Definition at line 59 of file Instrumenter.cc.
References Instrumentation::Values().
Referenced by Instrumenter::Instrument().
Instrument() [2/7]
bool Instrument (llvm::CallInst * , const Policy::Directions &)
Instrument a function call in the call and/or return direction.
Instrument() [3/7]
bool Instrument (llvm::CallInst * Call, Policy::Direction Dir)
Instrument a function call (caller-side), either calling or returning.
Definition at line 147 of file Instrumenter.cc.
References Instrumenter::Instrument().
Instrument() [4/7]
bool Instrument (llvm::Function & , const Policy::Directions &)
Instrument a function entry and/or exit.
Instrument() [5/7]
bool Instrument (llvm::Function & , Policy::Direction)
Instrument a function entry or exit.
Instrument() [6/7]
bool Instrument (llvm::GetElementPtrInst * , llvm::LoadInst * , llvm::StringRef FieldName)
Instrument a read from a structure field.
Instrument() [7/7]
bool Instrument (llvm::GetElementPtrInst * , llvm::StoreInst * , llvm::StringRef FieldName)
Instrument a write to a structure field.
The documentation for this class was generated from the following files:
src/Instrumenter.hh
src/Instrumenter.cc